import React from 'react';
import Head from 'next/head'
import { useState, useEffect } from 'react';
import styles from '@/styles/main.module.css'
import Link from 'next/link.js'
import {AiFillMessage, AiOutlineSearch, AiOutlineShoppingCart} from "react-icons/ai"
import { useRouter } from 'next/router.js';
import { useSelector, useDispatch } from 'react-redux'
import { incrementer } from '@/Features/counter/counterSlice.js'

function RankList(props) {
    // const router = useRouter()
    // const link = router.query.link
    const dispatch = useDispatch()  
    const [animeList, setAnimeList] = useState([])
    useEffect(() => {
        fetch('https://api.jikan.moe/v4/anime')
        .then(response => response.json())
        .then(data => setAnimeList(data.data));
    }, []);
    const favoriteList = [...animeList].sort((a, b) => b.favorites - a.favorites);

    return (
        <div>
        <Head>
        <title>All Time Popular</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
                <h3 className={styles.titleBig}>POPULARITY THIS SEASON</h3>
    <div className={styles.cards}>
    {favoriteList.map((anime) => {
        return(
        <div key={anime.mal_id} className={styles.card}>
        <Link href={`/${anime.mal_id}`}>
        <img className={styles.img} src={anime.images.webp.image_url} />
        </Link>
        <p  className={styles.width}>{anime.title}</p>
        <span className={styles.cart}  onClick={()=> dispatch(incrementer())}><AiOutlineShoppingCart/></span>

        <div className={styles.none}>
            <h5>{anime.type}  {anime.status} </h5>
            <p>{anime.genres.map((item)=>(<span className={styles.spanBadges}>{item.name}</span>))}</p>
            <p>{anime.source}</p>
            <div className={styles.triangle}></div>
        </div>
        </div>
    )})} 
        </div>
        </div>
    );
        // }
}

export default RankList;