import React from 'react';
import Link from "next/link.js";
import styles from '../styles/main.module.css'
import { useState, useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { setLoggedIn, setCurrentUser    } from '../Features/counter/counterSlice.js';
import Head from 'next/head'

function login(props) {
    const dispatch = useDispatch();
    const loggedIn = useSelector((state)=>state.counter.loggedIn)
    const [check, setCheck] = useState(true)
    const toCheck =()=>{
        setCheck(!check)
    }
    const [signInForm, setSignInForm] = useState({
        email: "",
        password: "",
    });

    const handleInputChange = (event) => {
        const { name, value } = event.target;
        setSignInForm({ ...signInForm, [name]: value });
    };
    const users = useSelector((state) => state.counter.users);

    const handleLogin = () => {
        const user = users.find(
            (user) =>
                user.email == signInForm.email &&
                user.password == signInForm.password
        );
        if (user && check==true) {
            dispatch(setLoggedIn(true));
            dispatch(setCurrentUser(user));
        }
    };

    const panier = useSelector((state)=>state.counter.cartItems);
if (loggedIn == false ){
    return (

        <div className={styles.loginPage}>        
        <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
            <div className={styles.form}>
                <h2>Login</h2>
                <input type="email" placeholder="Email" required name="email" value={signInForm.email} onChange={handleInputChange} />
                <input type="password" placeholder="Password" required name="password" value={signInForm.password} onChange={handleInputChange}/>
                <div className={styles.grey}>
                    <input type='checkbox' checked={check} onClick={toCheck} /><span>You agree to our terms of service</span>
                </div>
                <button onClick={handleLogin}>Login</button>
                <p className={styles.grey2}>Forgot password ?</p>
                <p className={styles.grey2}>Not registered ? <Link href='/SignUp'><span className={styles.blueLink}>Create an account</span></Link></p>
            </div>
        </div>
    );
} 
if (loggedIn == true ) {
    return(
        <div className={styles.loginPage}>  
            <h2 className={styles.bienvenue}>Welcome {signInForm.email}</h2>
        </div>
    )
}
}

export default login;